version: '3'

volumes:
  db:

services:
  # This launchees the database
  db:
    build:
      context: ./docker/psql
    env_file: ./docker/psql/psql.env
    volumes:
      - ./data:/data
    ports:
      - 5435:5432
  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      # The standard AMQP protocol port
      - '9672:5672'
      # HTTP management UI
      - '9673:15672'
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    command: redis-server --requirepass zaq12wsx
