create sequence hibernate_sequence start 1 increment 1;
create table article
(
    id            int8 generated by default as identity,
    creation_date timestamp with time zone,
    text          varchar(255),
    author_id     int8,
    primary key (id)
);
create table comment
(
    id            int8 generated by default as identity,
    creation_date timestamp  with time zone,
    text          varchar(255),
    article_id    int8,
    author_id     int8,
    primary key (id)
);
create table roles
(
    id   int8 not null,
    name varchar(60),
    primary key (id)
);
create table user_roles
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);
create table users
(
    id       int8 generated by default as identity,
    email    varchar(50),
    name     varchar(50),
    password varchar(100),
    username varchar(50),
    primary key (id)
);
alter table if exists roles
    add constraint UK_nb4h0p6txrmfc0xbrd1kglp9t unique (name);
alter table if exists users
    add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists users
    add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists article
    add constraint FKmjgtny2i22jf4dqncmd436s0u foreign key (author_id) references users;
alter table if exists comment
    add constraint FK5yx0uphgjc6ik6hb82kkw501y foreign key (article_id) references article;
alter table if exists comment
    add constraint FKir20vhrx08eh4itgpbfxip0s1 foreign key (author_id) references users;
alter table if exists user_roles
    add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles
    add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;